### PR TITLE
Issue#6 Implements the LIC6 method and tests

### LINKED ISSUE #6: Fix LIC 6
This feature will evaluate if the following is true or false for the input data points:

There exists at least one set of N_PTS consecutive data points such that at least one of the
points lies a distance greater than DIST from the line joining the first and last of these N_PTS
points. If the first and last points of these N_PTS are identical, then the calculated distance
to compare with DIST will be the distance from the coincident point to all other points of
the N_PTS consecutive points. The condition is not met when NUMPOINTS < 3.
(3 ≤ N_PTS ≤ NUMPOINTS), (0 ≤ DIST)

### PR DESCRIPTION
**Pull request by AnnaSkantz**
Implements LIC6(). Also implements 6 unit tests; 3 of them check positive and negative cases and the other 3 check that LIC6 is given valid input.

closes #6

### CODE REVIEW

**Comment by joakimAbdinurIusuf** [comment]
Please check line 195. I think it’s supposed to be && instead of & in the if-statement. Looks good otherwise, the logic is sound.

**Comment by AnnaSkantz** [comment]
Thanks, I agree. Will fix that!

**Comment by AnnaSkantz** [comment]
I noticed as well that I had not declared that the positive/negative test cases can throw the IllegalParameterObjectException, so I will add this too before merging.

**Comment by AnnaSkantz** [comment]
This is now fixed, so you can merge this branch

**Pull request merged**
