### PR TITLE
Adds test to the PUM function

### LINKED ISSUE #49: Test the PUM function more extensively
Create more tests for the PUM functions which gives it the wrong input. Right now ArrayIndexOutOfBounds can happen if you give a CMV whose length does not match the LCM matrix.

### PR DESCRIPTION
**Pull request by asta12**
Adds a test to test the PUM function when it receives input with wrong dimensions. There is also a fix which makes the program pass the test.

closes #49

### CODE REVIEW

**Comment by asta12** [comment]
Closes #49

**Comment by AnnaSkantz** [comment]
In the other tests on invalid input, we usually check that it outputs the correct exception message. Perhaps this is not needed here? 

One other detail is the method name "size()" as it is not very clear from the name what it does or that it is specific for the lcm matrix. A suggestion would be to change the name for the method to lcmSize() and to add JavaDoc since I think that we decided to add documentation to helper methods.

Everything else looks good to me.

**Comment by asta12** [comment]
I think that lcmSize() is a bit too much. You can only call it on the lcm object, so if I were to call it on my object named lcm it would be `lcm.lcmSize()`. You can think of the function as the `length()` function on a list.  

I will add javaDoc. I am a bit lazy when it comes to doc but it is important so it is good that you remind me. I will also add the check for the message to fit all the other tests.

**Comment by AnnaSkantz** [comment]
I agree with you about not changing the method name. I was confused about where the method was placed, and understand your reasoning now.

**Pull request merged**
