### PR TITLE
Issue#9 Implements LIC7 and unit tests

### LINKED ISSUE #9: Fix LIC 7
This feature will evaluate if the following is true or false for the input data points:

There exists at least one set of two data points separated by exactly K_PTS consecutive intervening points that are a distance greater than the length, LENGTH1, apart. The condition
is not met when NUMPOINTS < 3.
1 ≤ K_PTS ≤ (NUMPOINTS -2)

### PR DESCRIPTION
**Pull request by joakimAbdinurIusuf**
Implements the LIC7 method. Adds unit tests that check the positive and negative case, as well as exception handling for illegal values. All tests pass.

closes #9

### CODE REVIEW

**Comment by AnnaSkantz** [comment]
There seems to be some functionality missing in the LIC method.

**Comment by AnnaSkantz** [comment]
I see that the test cases seem to be in another order than what we have in the test file generally. From what I can tell we usually have all positive test cases first, then negative cases, and last all tests on Illegal input.

**Comment by AnnaSkantz** [comment]
I also do not agree with the documentation for this LIC "@return true if there exists two consecutive data points such that X_i+1 - X_i < 0". I think this is from another LIC.

**Comment by joakimAbdinurIusuf** [comment]
Added missing functionality, forgot to push. I'll fix the two other issues in a new issue and branch.

**Pull request closed without merging**
